# your_class = input("Enter your favorite class: ")
# loud_version = your_class.upper()
# print(loud_version)
class_name = input("what class are you taking next semester:")
num_credits = input("How many credits is it:")
print(f"You are taking {class_name} next semester for {num_credits} credits")